site_name: Mkdocs GH-Pages Example Site
site_description: Documentation
site_author: Joel Cumberland
site_url: https://jrosco.github.io/mkdocs-ghpages/

repo_name: jrosco/mkdocs-ghpages
repo_url: https://github.com/jrosco/

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Reference:
      - API: reference/api.md
      - CLI: reference/cli.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - attr_list

plugins:
  - search

# Optional: specify where your docs are
docs_dir: docs

